from fastapi import APIRouter


router = APIRouter()

@router.get("/alert")
def get_alerts() -> list:
    return [
        {
          "id": "1234",
          "alert_date": "04/20/2020 T2:00:00",
          "name": "Splunk Hunt: Example",
          "type": "splunk_hunter",
          "disposition": "FALSE_POSITIVE",
          "disposition_by": "Holly",
          "event_date": "04/20/2020 T2:00:00",
          "owner": "Holly",
          "queue": "default",
          "remediated_by": "Holly",
          "remediated_date": "04/20/2020 T2:00:00",
          "remediation_status": "remediated",
          "tags": ['bad', 'malware', 'oh_no'],
          "observables": [{'type': 'URL', 'value': 'http://www.google.com'},
            {'type': 'FQDN', 'value': 'google.com'},]
        },
        {
          "id": "2345",
          "alert_date": "04/20/2020 T2:00:00",
          "name": "Splunk Hunt: Example",
          "type": "splunk_hunter",
          "disposition": "FALSE_POSITIVE",
          "disposition_by": "Holly",
          "event_date": "04/20/2020 T2:00:00",
          "owner": "Holly",
          "queue": "default",
          "remediated_by": "Holly",
          "remediated_date": "04/20/2020 T2:00:00",
          "remediation_status": "remediated",
          "tags": ['bad', 'malware', 'oh_no'],
          "observables": [{'type': 'URL', 'value': 'http://www.google.com'},
            {'type': 'FQDN', 'value': 'google.com'},]
        },
        {
          "id": "3456",
          "alert_date": "04/20/2020 T2:00:00",
          "name": "Splunk Hunt: Example",
          "type": "splunk_hunter",
          "disposition": "FALSE_POSITIVE",
          "disposition_by": "Holly",
          "event_date": "04/20/2020 T2:00:00",
          "owner": "Holly",
          "queue": "default",
          "remediated_by": "Holly",
          "remediated_date": "04/20/2020 T2:00:00",
          "remediation_status": "remediated",
          "tags": ['bad', 'malware', 'oh_no'],
          "observables": [{'type': 'URL', 'value': 'http://www.google.com'},
            {'type': 'FQDN', 'value': 'google.com'},]
        },
        {
          "id": "4567",
          "alert_date": "04/20/2020 T2:00:00",
          "name": "Splunk Hunt: Example",
          "type": "splunk_hunter",
          "disposition": "FALSE_POSITIVE",
          "disposition_by": "Holly",
          "event_date": "04/20/2020 T2:00:00",
          "owner": "Holly",
          "queue": "default",
          "remediated_by": "Holly",
          "remediated_date": "04/20/2020 T2:00:00",
          "remediation_status": "remediated",
          "tags": ['bad', 'malware', 'oh_no'],
          "observables": [{'type': 'URL', 'value': 'http://www.google.com'},
            {'type': 'FQDN', 'value': 'google.com'},]
        },
        {
          "id": "5678",
          "alert_date": "04/20/2020 T2:00:00",
          "name": "Splunk Hunt: Example",
          "type": "splunk_hunter",
          "disposition": "FALSE_POSITIVE",
          "disposition_by": "Holly",
          "event_date": "04/20/2020 T2:00:00",
          "owner": "Holly",
          "queue": "default",
          "remediated_by": "Holly",
          "remediated_date": "04/20/2020 T2:00:00",
          "remediation_status": "remediated",
          "tags": ['bad', 'malware', 'oh_no'],
          "observables": [{'type': 'URL', 'value': 'http://www.google.com'},
            {'type': 'FQDN', 'value': 'google.com'},]
        },
        {
          "id": "6789",
          "alert_date": "04/20/2020 T2:00:00",
          "name": "Splunk Hunt: Example",
          "type": "splunk_hunter",
          "disposition": "FALSE_POSITIVE",
          "disposition_by": "Holly",
          "event_date": "04/20/2020 T2:00:00",
          "owner": "Holly",
          "queue": "default",
          "remediated_by": "Holly",
          "remediated_date": "04/20/2020 T2:00:00",
          "remediation_status": "remediated",
          "tags": ['bad', 'malware', 'oh_no'],
          "observables": [{'type': 'URL', 'value': 'http://www.google.com'},
            {'type': 'FQDN', 'value': 'google.com'},]
        },
        {
          "id": "7890",
          "alert_date": "04/20/2020 T2:00:00",
          "name": "Splunk Hunt: Example",
          "type": "splunk_hunter",
          "disposition": "FALSE_POSITIVE",
          "disposition_by": "Holly",
          "event_date": "04/20/2020 T2:00:00",
          "owner": "Holly",
          "queue": "default",
          "remediated_by": "Holly",
          "remediated_date": "04/20/2020 T2:00:00",
          "remediation_status": "remediated",
          "tags": ['bad', 'malware', 'oh_no'],
          "observables": [{'type': 'URL', 'value': 'http://www.google.com'},
            {'type': 'FQDN', 'value': 'google.com'},]
        },
        {
          "id": "0978",
          "alert_date": "04/20/2020 T2:00:00",
          "name": "Splunk Hunt: Example",
          "type": "splunk_hunter",
          "disposition": "FALSE_POSITIVE",
          "disposition_by": "Holly",
          "event_date": "04/20/2020 T2:00:00",
          "owner": "Holly",
          "queue": "default",
          "remediated_by": "Holly",
          "remediated_date": "04/20/2020 T2:00:00",
          "remediation_status": "remediated",
          "tags": ['bad', 'malware', 'oh_no'],
          "observables": [{'type': 'URL', 'value': 'http://www.google.com'},
            {'type': 'FQDN', 'value': 'google.com'},]
        },
      ]