FROM node:lts-alpine
WORKDIR /app
COPY frontend/app/package*.json ./
RUN apk --no-cache add --virtual native-deps \
  g++ gcc libgcc libstdc++ linux-headers make python && \
  npm install --quiet node-gyp -g && \
  npm install --quiet && \
  apk del native-deps
COPY frontend/app/ ./
CMD ["npm", "run", "serve"]