"""Initial

Revision ID: fb94039d7a4d
Revises: 
Create Date: 2021-06-25 15:53:35.301388
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision = 'fb94039d7a4d'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_disposition',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('rank')
    )
    op.create_index(op.f('ix_alert_disposition_value'), 'alert_disposition', ['value'], unique=True)
    op.create_table('alert_queue',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_alert_queue_value'), 'alert_queue', ['value'], unique=True)
    op.create_table('alert_type',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_alert_type_value'), 'alert_type', ['value'], unique=True)
    op.create_table('analysis_module_type',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('manual', sa.Boolean(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_analysis_module_type_value'), 'analysis_module_type', ['value'], unique=True)
    op.create_table('event_prevention_tool',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_event_prevention_tool_value'), 'event_prevention_tool', ['value'], unique=True)
    op.create_table('event_remediation',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_event_remediation_value'), 'event_remediation', ['value'], unique=True)
    op.create_table('event_risk_level',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_event_risk_level_value'), 'event_risk_level', ['value'], unique=True)
    op.create_table('event_source',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_event_source_value'), 'event_source', ['value'], unique=True)
    op.create_table('event_status',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_event_status_value'), 'event_status', ['value'], unique=True)
    op.create_table('event_type',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_event_type_value'), 'event_type', ['value'], unique=True)
    op.create_table('event_vector',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_event_vector_value'), 'event_vector', ['value'], unique=True)
    op.create_table('node_directive',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_node_directive_value'), 'node_directive', ['value'], unique=True)
    op.create_table('node_history_action',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_node_history_action_value'), 'node_history_action', ['value'], unique=True)
    op.create_table('node_tag',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_node_tag_value'), 'node_tag', ['value'], unique=True)
    op.create_table('node_threat',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_node_threat_value'), 'node_threat', ['value'], unique=True)
    op.create_table('node_threat_actor',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_node_threat_actor_value'), 'node_threat_actor', ['value'], unique=True)
    op.create_table('node_threat_type',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_node_threat_type_value'), 'node_threat_type', ['value'], unique=True)
    op.create_table('observable_type',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_observable_type_value'), 'observable_type', ['value'], unique=True)
    op.create_table('user_role',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_user_role_value'), 'user_role', ['value'], unique=True)
    op.create_table('analysis_module_type_observable_type_mapping',
    sa.Column('analysis_module_type_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('observable_type_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_module_type_uuid'], ['analysis_module_type.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['observable_type_uuid'], ['observable_type.uuid'], ),
    sa.PrimaryKeyConstraint('analysis_module_type_uuid', 'observable_type_uuid')
    )
    op.create_index(op.f('ix_analysis_module_type_observable_type_mapping_analysis_module_type_uuid'), 'analysis_module_type_observable_type_mapping', ['analysis_module_type_uuid'], unique=False)
    op.create_table('node',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('node_type', sa.String(), nullable=True),
    sa.Column('threat_actor_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['threat_actor_uuid'], ['node_threat_actor.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('node_threat_node_threat_type_mapping',
    sa.Column('node_threat_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('node_threat_type_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['node_threat_type_uuid'], ['node_threat_type.uuid'], ),
    sa.ForeignKeyConstraint(['node_threat_uuid'], ['node_threat.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('node_threat_uuid', 'node_threat_type_uuid')
    )
    op.create_index(op.f('ix_node_threat_node_threat_type_mapping_node_threat_uuid'), 'node_threat_node_threat_type_mapping', ['node_threat_uuid'], unique=False)
    op.create_table('observable',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('expires_on', sa.DateTime(), nullable=True),
    sa.Column('for_detection', sa.Boolean(), nullable=True),
    sa.Column('type_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['type_uuid'], ['observable_type.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('type_uuid', 'value', name='type_value_uc')
    )
    op.create_index('type_value', 'observable', ['type_uuid', 'value'], unique=False)
    op.create_index('value_trgm', 'observable', ['value'], unique=False, postgresql_ops={'value': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_table('analysis',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('analysis_module_type_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('event_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('module_extended_version', sa.String(), nullable=True),
    sa.Column('module_version', sa.String(), nullable=True),
    sa.Column('stack_trace', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_module_type_uuid'], ['analysis_module_type.uuid'], ),
    sa.ForeignKeyConstraint(['uuid'], ['node.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('node_directive_mapping',
    sa.Column('node_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('directive_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['directive_uuid'], ['node_directive.uuid'], ),
    sa.ForeignKeyConstraint(['node_uuid'], ['node.uuid'], ),
    sa.PrimaryKeyConstraint('node_uuid', 'directive_uuid')
    )
    op.create_index(op.f('ix_node_directive_mapping_node_uuid'), 'node_directive_mapping', ['node_uuid'], unique=False)
    op.create_table('node_tag_mapping',
    sa.Column('node_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tag_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['node_uuid'], ['node.uuid'], ),
    sa.ForeignKeyConstraint(['tag_uuid'], ['node_tag.uuid'], ),
    sa.PrimaryKeyConstraint('node_uuid', 'tag_uuid')
    )
    op.create_index(op.f('ix_node_tag_mapping_node_uuid'), 'node_tag_mapping', ['node_uuid'], unique=False)
    op.create_table('node_threat_mapping',
    sa.Column('node_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('threat_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['node_uuid'], ['node.uuid'], ),
    sa.ForeignKeyConstraint(['threat_uuid'], ['node_threat.uuid'], ),
    sa.PrimaryKeyConstraint('node_uuid', 'threat_uuid')
    )
    op.create_index(op.f('ix_node_threat_mapping_node_uuid'), 'node_threat_mapping', ['node_uuid'], unique=False)
    op.create_table('user',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('default_alert_queue_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['default_alert_queue_uuid'], ['alert_queue.uuid'], ),
    sa.ForeignKeyConstraint(['uuid'], ['node.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('comment',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('insert_time', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('node_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('user_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['node_uuid'], ['node.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('node_uuid', 'comment', ['node_uuid'], unique=False)
    op.create_table('event',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('alert_time', sa.DateTime(), nullable=True),
    sa.Column('contain_time', sa.DateTime(), nullable=True),
    sa.Column('creation_time', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('disposition_time', sa.DateTime(), nullable=True),
    sa.Column('event_time', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('owner_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('ownership_time', sa.DateTime(), nullable=True),
    sa.Column('remediation_time', sa.DateTime(), nullable=True),
    sa.Column('risk_level_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('source_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('status_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('type_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['risk_level_uuid'], ['event_risk_level.uuid'], ),
    sa.ForeignKeyConstraint(['source_uuid'], ['event_source.uuid'], ),
    sa.ForeignKeyConstraint(['status_uuid'], ['event_status.uuid'], ),
    sa.ForeignKeyConstraint(['type_uuid'], ['event_type.uuid'], ),
    sa.ForeignKeyConstraint(['uuid'], ['node.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('node_history',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('action_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('action_user_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('node_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.ForeignKeyConstraint(['action_user_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['action_uuid'], ['node_history_action.uuid'], ),
    sa.ForeignKeyConstraint(['node_uuid'], ['node.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('user_role_mapping',
    sa.Column('user_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_role_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['user_role_uuid'], ['user_role.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('user_uuid', 'user_role_uuid')
    )
    op.create_index(op.f('ix_user_role_mapping_user_uuid'), 'user_role_mapping', ['user_uuid'], unique=False)
    op.create_table('alert',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('alert_type_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('disposition_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('disposition_time', sa.DateTime(), nullable=True),
    sa.Column('disposition_user_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('event_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('insert_time', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('owner_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('queue_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('tool', sa.String(), nullable=True),
    sa.Column('tool_instance', sa.String(), nullable=True),
    sa.Column('version', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['alert_type_uuid'], ['alert_type.uuid'], ),
    sa.ForeignKeyConstraint(['disposition_user_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['disposition_uuid'], ['alert_disposition.uuid'], ),
    sa.ForeignKeyConstraint(['event_uuid'], ['event.uuid'], ),
    sa.ForeignKeyConstraint(['owner_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['queue_id'], ['alert_queue.uuid'], ),
    sa.ForeignKeyConstraint(['uuid'], ['analysis.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('event_uuid', 'alert', ['event_uuid'], unique=False)
    op.create_table('event_prevention_tool_mapping',
    sa.Column('event_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('prevention_tool_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['event_uuid'], ['event.uuid'], ),
    sa.ForeignKeyConstraint(['prevention_tool_uuid'], ['event_prevention_tool.uuid'], ),
    sa.PrimaryKeyConstraint('event_uuid', 'prevention_tool_uuid')
    )
    op.create_index(op.f('ix_event_prevention_tool_mapping_event_uuid'), 'event_prevention_tool_mapping', ['event_uuid'], unique=False)
    op.create_table('event_remediation_mapping',
    sa.Column('event_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('remediation_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['event_uuid'], ['event.uuid'], ),
    sa.ForeignKeyConstraint(['remediation_uuid'], ['event_remediation.uuid'], ),
    sa.PrimaryKeyConstraint('event_uuid', 'remediation_uuid')
    )
    op.create_index(op.f('ix_event_remediation_mapping_event_uuid'), 'event_remediation_mapping', ['event_uuid'], unique=False)
    op.create_table('event_vector_mapping',
    sa.Column('event_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('vector_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['event_uuid'], ['event.uuid'], ),
    sa.ForeignKeyConstraint(['vector_uuid'], ['event_vector.uuid'], ),
    sa.PrimaryKeyConstraint('event_uuid', 'vector_uuid')
    )
    op.create_index(op.f('ix_event_vector_mapping_event_uuid'), 'event_vector_mapping', ['event_uuid'], unique=False)
    op.create_table('observable_instance',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('alert_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('observable_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('redirection', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('time', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.ForeignKeyConstraint(['alert_uuid'], ['alert.uuid'], ),
    sa.ForeignKeyConstraint(['observable_uuid'], ['observable.uuid'], ),
    sa.ForeignKeyConstraint(['redirection'], ['observable_instance.uuid'], ),
    sa.ForeignKeyConstraint(['uuid'], ['node.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('analysis_observable_instance_mapping',
    sa.Column('analysis_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('observable_instance_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_uuid'], ['analysis.uuid'], ),
    sa.ForeignKeyConstraint(['observable_instance_uuid'], ['observable_instance.uuid'], ),
    sa.PrimaryKeyConstraint('analysis_uuid', 'observable_instance_uuid')
    )
    op.create_index(op.f('ix_analysis_observable_instance_mapping_analysis_uuid'), 'analysis_observable_instance_mapping', ['analysis_uuid'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_observable_instance_mapping_analysis_uuid'), table_name='analysis_observable_instance_mapping')
    op.drop_table('analysis_observable_instance_mapping')
    op.drop_table('observable_instance')
    op.drop_index(op.f('ix_event_vector_mapping_event_uuid'), table_name='event_vector_mapping')
    op.drop_table('event_vector_mapping')
    op.drop_index(op.f('ix_event_remediation_mapping_event_uuid'), table_name='event_remediation_mapping')
    op.drop_table('event_remediation_mapping')
    op.drop_index(op.f('ix_event_prevention_tool_mapping_event_uuid'), table_name='event_prevention_tool_mapping')
    op.drop_table('event_prevention_tool_mapping')
    op.drop_index('event_uuid', table_name='alert')
    op.drop_table('alert')
    op.drop_index(op.f('ix_user_role_mapping_user_uuid'), table_name='user_role_mapping')
    op.drop_table('user_role_mapping')
    op.drop_table('node_history')
    op.drop_table('event')
    op.drop_index('node_uuid', table_name='comment')
    op.drop_table('comment')
    op.drop_table('user')
    op.drop_index(op.f('ix_node_threat_mapping_node_uuid'), table_name='node_threat_mapping')
    op.drop_table('node_threat_mapping')
    op.drop_index(op.f('ix_node_tag_mapping_node_uuid'), table_name='node_tag_mapping')
    op.drop_table('node_tag_mapping')
    op.drop_index(op.f('ix_node_directive_mapping_node_uuid'), table_name='node_directive_mapping')
    op.drop_table('node_directive_mapping')
    op.drop_table('analysis')
    op.drop_index('value_trgm', table_name='observable')
    op.drop_index('type_value', table_name='observable')
    op.drop_table('observable')
    op.drop_index(op.f('ix_node_threat_node_threat_type_mapping_node_threat_uuid'), table_name='node_threat_node_threat_type_mapping')
    op.drop_table('node_threat_node_threat_type_mapping')
    op.drop_table('node')
    op.drop_index(op.f('ix_analysis_module_type_observable_type_mapping_analysis_module_type_uuid'), table_name='analysis_module_type_observable_type_mapping')
    op.drop_table('analysis_module_type_observable_type_mapping')
    op.drop_index(op.f('ix_user_role_value'), table_name='user_role')
    op.drop_table('user_role')
    op.drop_index(op.f('ix_observable_type_value'), table_name='observable_type')
    op.drop_table('observable_type')
    op.drop_index(op.f('ix_node_threat_type_value'), table_name='node_threat_type')
    op.drop_table('node_threat_type')
    op.drop_index(op.f('ix_node_threat_actor_value'), table_name='node_threat_actor')
    op.drop_table('node_threat_actor')
    op.drop_index(op.f('ix_node_threat_value'), table_name='node_threat')
    op.drop_table('node_threat')
    op.drop_index(op.f('ix_node_tag_value'), table_name='node_tag')
    op.drop_table('node_tag')
    op.drop_index(op.f('ix_node_history_action_value'), table_name='node_history_action')
    op.drop_table('node_history_action')
    op.drop_index(op.f('ix_node_directive_value'), table_name='node_directive')
    op.drop_table('node_directive')
    op.drop_index(op.f('ix_event_vector_value'), table_name='event_vector')
    op.drop_table('event_vector')
    op.drop_index(op.f('ix_event_type_value'), table_name='event_type')
    op.drop_table('event_type')
    op.drop_index(op.f('ix_event_status_value'), table_name='event_status')
    op.drop_table('event_status')
    op.drop_index(op.f('ix_event_source_value'), table_name='event_source')
    op.drop_table('event_source')
    op.drop_index(op.f('ix_event_risk_level_value'), table_name='event_risk_level')
    op.drop_table('event_risk_level')
    op.drop_index(op.f('ix_event_remediation_value'), table_name='event_remediation')
    op.drop_table('event_remediation')
    op.drop_index(op.f('ix_event_prevention_tool_value'), table_name='event_prevention_tool')
    op.drop_table('event_prevention_tool')
    op.drop_index(op.f('ix_analysis_module_type_value'), table_name='analysis_module_type')
    op.drop_table('analysis_module_type')
    op.drop_index(op.f('ix_alert_type_value'), table_name='alert_type')
    op.drop_table('alert_type')
    op.drop_index(op.f('ix_alert_queue_value'), table_name='alert_queue')
    op.drop_table('alert_queue')
    op.drop_index(op.f('ix_alert_disposition_value'), table_name='alert_disposition')
    op.drop_table('alert_disposition')
    # ### end Alembic commands ###